name: Build, Format, Lint and Test
on:
  workflow_dispatch:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
    - 'main'
    - 'releases/*'

jobs:
  # Build the package
  # echo "::set-output name=version::$(cat .python-version)" >> $GITHUB_ENV
  build:
    name: Build py-fatigue
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get python version from .python-version
      id: python-version
      run: |
        echo "version=$(cat .python-version)" >> $GITHUB_ENV

    - name: Install python ${{ steps.python-version.outputs.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Install poetry
      uses: Gr1N/setup-poetry@v7

    - name: Build package
      run: poetry build

    - name: Upload built package
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
        retention-days: 1

  # Run black
  black:
    name: Black formatter
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get python version from .python-version
      id: python-version
      run: |
        echo "version=$(cat .python-version)" >> $GITHUB_ENV

    - name: Install python ${{ steps.python-version.outputs.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Install Dependencies
      run: |
        pip install black
    - name: Run black
      run: |
        black py_fatigue/ --check

  # Run flake8
  flake8_py3:
    name: Flake8 Linter
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get python version from .python-version
      id: python-version
      run: |
        echo "version=$(cat .python-version)" >> $GITHUB_ENV

    - name: Install python ${{ steps.python-version.outputs.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Install Dependencies
      run: |
        pip install flake8
    - name: Run flake8
      run: |
        flake8 py_fatigue/ --count --select=E9,F63,F7,F82 --show-source --statistics

  # Run mypy
  mypy:
    name: Mypy Type Checker
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get python version from .python-version
      id: python-version
      run: |
        echo "version=$(cat .python-version)" >> $GITHUB_ENV

    - name: Install python ${{ steps.python-version.outputs.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Install Dependencies
      run: |
        pip install mypy

    - name: Run mypy
      run: |
        mypy --config-file=./mypy.ini py_fatigue/

  # Run pytest using built package
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip'
        cache-dependency-path: "poetry.lock"

    - name: Download built package
      uses: actions/download-artifact@v3
      with:
        name: dist
    
    - name: Install py_fatigue and pytest
      shell: bash
      run: |
        WHL_NAME=$(ls py_fatigue-*.whl)
        pip install ${WHL_NAME} pytest hypothesis
    - name: Run tests
      shell: bash
      run: pytest
