name: CI/CD
on:
  # push:
  #   branches: [main]
  # pull_request:
  workflow_call:
    inputs:
      bumptype:
        required: true
        type: string
      publish_to_test_pypi:
        required: true
        type: boolean
      publish_to_pypi:
        required: true
        type: boolean
  workflow_dispatch:
    inputs:
      bumptype:
        type: choice
        description: ''
        options:
        - patch
        - minor
        - major

jobs:
  bump-and-build:
    name: bump-and-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python
      run: uv python install 3.10
    - name: Bump version
      run: |
        uv run bumpversion.py ${{ github.event.inputs.bumptype }}
        NEW_VERSION=$(grep -Po '(?<=__version__: str = ")[^"]+' ${{ github.workspace }}/py_fatigue/version.py)
        git config --local user.email pietro.dantuono@vub.be
        git config --local user.name "Pitro D'Antuono"
        git checkout -b release/v$NEW_VERSION
        git commit -am "bump(${{ github.event.inputs.bumptype }}): Bump version to $NEW_VERSION [skip ci]"
        if [ $(git tag -l "v$NEW_VERSION") ]; then
            echo yes
        else
            git tag v$NEW_VERSION
            git push origin release/v$NEW_VERSION --tags
        fi
        # Merge changes to 'refs/heads/main'
        git fetch origin main
        git checkout main
        git merge --no-ff release/v$NEW_VERSION -m "ci(pipeline): Merge release/v$NEW_VERSION to main [skip ci]"
        git push origin main
        uv build --out-dir dist-3.10
    - name: Upload built package
      uses: actions/upload-artifact@v4
      with:
        name: dist-3.10
        path: dist-3.10/
        retention-days: 1