name: CI/CD
on:
  # push:
  #   branches: [main]
  # pull_request:
  workflow_dispatch:
    inputs:
      bumptype:
        type: choice
        description: ''
        options:
        - patch
        - minor
        - major
      publish_to_test_pypi:
        type: boolean
        description: 'Publish to Test PyPI'
        required: true
        default: false
      publish_to_pypi:
        type: boolean
        description: 'Publish to PyPI'
        required: true
        default: true

env:
  PUBLISH_TO_TEST_PYPI: ${{ github.event.inputs.publish_to_test_pypi }}
  PUBLISH_TO_PYPI: ${{ github.event.inputs.publish_to_pypi }}

jobs:

  ci:
    uses: ./.github/workflows/ci.yml

  bump-and-build:
    # needs: [ci]
    uses: ./.github/workflows/bump-and-build.yml

  cd:
    name: cd
    needs: [bump-and-build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - name: Download built package
      uses: actions/download-artifact@v4
      with:
        name: dist-3.10
        path: dist-3.10
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Publish distribution 📦 to Test PyPI
      if: env.PUBLISH_TO_TEST_PYPI == 'true' || env.PUBLISH_TO_TEST_PYPI == true
      run: uv publish --publish-url https://test.pypi.org/legacy/ dist-3.10/* -t ${{ secrets.PYPI_TEST_API_TOKEN }}
    - name: Publish distribution 📦 to PyP
      if: env.PUBLISH_TO_PYPI == 'true' || env.PUBLISH_TO_PYPI == true
      run: uv publish dist-3.10/* -t ${{ secrets.PYPI_API_TOKEN }}
