name: CI/CD
on:
  # push:
  #   branches: [main]
  # pull_request:
  workflow_dispatch:
    inputs:
      bumptype:
        type: choice
        description: ''
        options:
        - patch
        - minor
        - major
      publish_to_test_pypi:
        type: boolean
        description: 'Publish to Test PyPI'
        required: true
        default: false
      publish_to_pypi:
        type: boolean
        description: 'Publish to PyPI'
        required: true
        default: true

env:
  PUBLISH_TO_TEST_PYPI: ${}
  PUBLISH_TO_PYPI: ${{ github.event.inputs.publish_to_pypi }}

jobs:
  ci:
    uses: ./.github/workflows/ci.yml  # use the callable tests job to run tests

  bump:
    name: bump
    # needs: [ci]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python
      run: uv python install
    - name: Bump version
      run: |
        uv run bumpversion.py ${{ github.event.inputs.bumptype }}
        NEW_VERSION=$(grep -Po '(?<=__version__: str = ")[^"]+' $(Build.SourcesDirectory)/api_24sea/version.py)
        git config --local user.email github.actions@vub.be
        git config --local user.name "GitHub Actions Pipeline"
        git checkout -b release/v$NEW_VERSION
        git commit -am "bump(${{ github.event.inputs.bumptype }}): Bump version to $NEW_VERSION [skip ci]"
        if [ $(git tag -l "v$NEW_VERSION") ]; then
            echo yes
        else
            git tag v$NEW_VERSION
            git push origin release/v$NEW_VERSION --tags
        fi
        # Merge changes to 'refs/heads/main'
        git fetch origin main
        git checkout main
        git merge --no-ff release/v$NEW_VERSION -m "ci(pipeline): Merge release/v$NEW_VERSION to main [skip ci]"
        git push origin main

  build:
    name: build
    needs: [bump]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Set up Python
      run: uv python install
    - name: Install the project
      run: uv sync

    - name: Build package
      run: uv build --out-dir dist-${{ matrix.python-version }}

    - name: Upload built package
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.python-version }}
        path: dist-${{ matrix.python-version }}/
        retention-days: 1
  cd:
    name: cd
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download built package
      uses: actions/download-artifact@v4
      with:
        name: dist-3.10
        path: dist-3.10
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Publish distribution 📦 to Test PyPI
      if: env.PUBLISH_TO_TEST_PYPI == 'true' || env.PUBLISH_TO_TEST_PYPI == true
      run: uv publish --publish-url https://test.pypi.org/legacy/ dist-3.10/* -t ${{ secrets.PYPI_TEST_API_TOKEN }}
    - name: Publish distribution 📦 to PyP
      if: env.PUBLISH_TO_PYPI == 'true' || env.PUBLISH_TO_PYPI == true
      run: uv publish dist-3.10/* -t ${{ secrets.PYPI_API_TOKEN }}
