name: Linting

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:
    branches:
      - main

jobs:
  # Build the package
  # echo "::set-output name=version::$(cat .python-version)" >> $GITHUB_ENV
  build:
    name: Build py-fatigue
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get python version from .python-version
      id: python-version
      run: |
        echo "version=$(cat .python-version)" >> $GITHUB_ENV

    - name: Install python ${{ steps.python-version.outputs.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Install poetry
      uses: Gr1N/setup-poetry@v7

    - name: Build package
      run: poetry build

    - name: Upload built package
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
        retention-days: 1

  # Run black
  black:
    name: Black formatter
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get python version from .python-version
      id: python-version
      run: |
        echo "version=$(cat .python-version)" >> $GITHUB_ENV

    - name: Install python ${{ steps.python-version.outputs.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Install Dependencies
      run: |
        pip install black
    - name: Run black
      run: |
        black py_fatigue/ --check

  # Run flake8
  flake8_py3:
    name: Flake8 Linter
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get python version from .python-version
      id: python-version
      run: |
        echo "version=$(cat .python-version)" >> $GITHUB_ENV

    - name: Install python ${{ steps.python-version.outputs.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Install Dependencies
      run: |
        pip install flake8
    - name: Run flake8
      run: |
        flake8 py_fatigue/ --count --select=E9,F63,F7,F82 --show-source --statistics

  # Run mypy
  mypy:
    name: Mypy Type Checker
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get python version from .python-version
      id: python-version
      run: |
        echo "version=$(cat .python-version)" >> $GITHUB_ENV

    - name: Install python ${{ steps.python-version.outputs.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.python-version.outputs.version }}

    - name: Install Dependencies
      run: |
        pip install mypy

    - name: Run mypy
      run: |
        mypy --config-file=./mypy.ini py_fatigue/

  # Run pytest
  gist:
    name: Gist badges
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: pd_gist
        filename: py-fatigue.json
        label: Hello
        message: World
        color: orange
