name: Publish to GitHub Pages

on: [push, pull_request, workflow_dispatch, workflow_call]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    # if: contains(github.event.head_commit.message, '[publish pages]')
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --group docs
      - name: Sphinx build
        run: |
          uv run sphinx-build -b  html -d rst_docs/doctrees ./rst_docs _build/docs -E -a
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop') }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/docs
          force_orphan: true
